    if (PyErr_Occurred()) goto craft_error;